/* Autogenerated – DO NOT EDIT */

pub mod line_terminator;
pub use line_terminator::line_terminator_p;
pub mod pattern_white_space;
pub use pattern_white_space::pattern_white_space_p;
pub mod xid_continue;
pub use xid_continue::xid_continue_p;
pub mod xid_start;
pub use xid_start::xid_start_p;
